import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import SideNav from "@/components/SideNav";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid grid-cols-6 container">
          <nav className="xl:col-span-1">
            <SideNav />
          </nav>
          <div className="col-span-6 xl:col-span-5">{children}</div>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
